################################################################################
#
# DigitalRoosterGui
#
################################################################################

ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_VERSION_DEVEL))
	DIGITALROOSTERGUI_VERSION = develop
	DIGITALROOSTERGUI_SITE = https://github.com/truschival/DigitalRoosterGui.git
	DIGITALROOSTERGUI_SITE_METHOD = git
else
	DIGITALROOSTERGUI_VERSION = v0.10.2
	DIGITALROOSTERGUI_SOURCE = $(DIGITALROOSTERGUI_VERSION).tar.gz
	DIGITALROOSTERGUI_SITE = https://github.com/truschival/DigitalRoosterGui/archive
	DIGITALROOSTERGUI_SITE_METHOD = wget
endif

DIGITALROOSTERGUI_INSTALL_STAGING = YES
DIGITALROOSTERGUI_INSTALL_TARGET = YES
DIGITALROOSTERGUI_LICENSE = GPL-3.0+
DIGITALROOSTERGUI_LICENSE_FILES = LICENSE

##
# Build Configuration
##
DIGITALROOSTERGUI_CONF_OPTS += -DSYSTEM_TARGET_NAME=RPi

# Debug config
ifeq (y, $(BR2_PACKAGE_DIGITALROOSTERGUI_DEBUG))
	DIGITALROOSTERGUI_CONF_OPTS += -G "Eclipse CDT4 - Unix Makefiles"
	DIGITALROOSTERGUI_CONF_OPTS += -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=true
	DIGITALROOSTERGUI_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

ifeq (y , $(BR2_PACKAGE_WPA_SUPPLICANT))
	DIGITALROOSTERGUI_CONF_OPTS += -DHAS_WPA_SUPPLICANT=On
endif

ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_REST))
	DIGITALROOSTERGUI_CONF_OPTS += -DREST_API=On
	DIGITALROOSTERGUI_CONF_OPTS += \
		-DREST_API_PORT=$(BR2_PACKAGE_DIGITALROOSTERGUI_REST_PORT)
endif

# Build with tests, user must copy the binary and support files manually
ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_TEST))
       DIGITALROOSTERGUI_CONF_OPTS += -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF
endif #tests

# Deploy custom config
ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_CUSTOM_CONFIG))
	DIGITALROOSTERGUI_CONFIG_FILE = \
		$(BR2_PACKAGE_DIGITALROOSTERGUI_CUSTOM_CONFIG_FILE)
else
	DIGITALROOSTERGUI_CONFIG_FILE = \
		$(DIGITALROOSTERGUI_PKGDIR)/digitalrooster.json
endif

#install start script
define DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT
	$(INSTALL) -m 0755 $(DIGITALROOSTERGUI_PKGDIR)/S99digitalrooster.sh \
		$(TARGET_DIR)/etc/init.d/
	$(INSTALL) -D -m 0644 $(DIGITALROOSTERGUI_PKGDIR)/digitalrooster-qt.conf \
		$(TARGET_DIR)/etc/default/digitalrooster-qt.conf
	$(INSTALL) -D -m 0644 $(DIGITALROOSTERGUI_CONFIG_FILE) \
		$(TARGET_DIR)/persistent/digitalrooster.json
endef

# Register post install hooks
DIGITALROOSTERGUI_POST_INSTALL_TARGET_HOOKS += \
	DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT \
	DIGITALROOSTERGUI_POST_INSTALL_UNIT_TEST_TO_TARGET

$(eval $(cmake-package))
