################################################################################
#
# DigitalRoosterGui
#
################################################################################

ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_VERSION_DEVEL))
DIGITALROOSTERGUI_VERSION = develop
DIGITALROOSTERGUI_SITE = https://github.com/truschival/DigitalRoosterGui.git
DIGITALROOSTERGUI_SITE_METHOD = git
else
DIGITALROOSTERGUI_VERSION = v0.11
DIGITALROOSTERGUI_SITE = $(call github,truschival,DigitalRoosterGui,$(DIGITALROOSTERGUI_VERSION))
endif

DIGITALROOSTERGUI_LICENSE = GPL-3.0+
DIGITALROOSTERGUI_LICENSE_FILES = LICENSE
DIGITALROOSTERGUI_INSTALL_STAGING = YES

##
# Build Configuration
##
DIGITALROOSTERGUI_CONF_OPTS += -DSYSTEM_TARGET_NAME=Embedded

# Debug config
ifeq (y, $(BR2_PACKAGE_DIGITALROOSTERGUI_DEBUG))
DIGITALROOSTERGUI_CONF_OPTS += -G "Eclipse CDT4 - Unix Makefiles"
DIGITALROOSTERGUI_CONF_OPTS += -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=true
DIGITALROOSTERGUI_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

ifeq (y , $(BR2_PACKAGE_WPA_SUPPLICANT))
DIGITALROOSTERGUI_CONF_OPTS += -DHAS_WPA_SUPPLICANT=On
endif

ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_REST))
DIGITALROOSTERGUI_DEPENDENCIES += pistache
DIGITALROOSTERGUI_CONF_OPTS += -DREST_API=On
DIGITALROOSTERGUI_CONF_OPTS += \
	-DREST_API_PORT=$(BR2_PACKAGE_DIGITALROOSTERGUI_REST_PORT)
endif

# Build with tests, user must copy the binary and support files manually
ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_TEST))
DIGITALROOSTERGUI_CONF_OPTS += -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF
endif #tests

# Deploy custom config
ifeq (y , $(BR2_PACKAGE_DIGITALROOSTERGUI_CUSTOM_CONFIG))
DIGITALROOSTERGUI_CONFIG_FILE = \
	$(BR2_PACKAGE_DIGITALROOSTERGUI_CUSTOM_CONFIG_FILE)
else
DIGITALROOSTERGUI_CONFIG_FILE = \
	$(DIGITALROOSTERGUI_PKGDIR)/digitalrooster.json
endif

#install start script
define DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT
	$(INSTALL) -m 0755 $(DIGITALROOSTERGUI_PKGDIR)/S99digitalrooster.sh \
	$(TARGET_DIR)/etc/init.d/
	$(INSTALL) -D -m 0644 $(DIGITALROOSTERGUI_PKGDIR)/digitalrooster.conf \
	$(TARGET_DIR)/etc/default/digitalrooster.conf
	$(INSTALL) -D -m 0644 $(DIGITALROOSTERGUI_CONFIG_FILE) \
	$(TARGET_DIR)/persistent/digitalrooster.json
endef

# install crontab from monitor and processmonitor/restart script
define DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT_PROCMON
	$(INSTALL) -D -m 0755 $(DIGITALROOSTERGUI_PKGDIR)/procmon.sh \
	$(TARGET_DIR)/usr/bin/procmon.sh
	$(INSTALL) -D -m 0644 $(DIGITALROOSTERGUI_PKGDIR)/check_digitalrooster \
	$(TARGET_DIR)/etc/cron.d
endef


# Register post install hooks
DIGITALROOSTERGUI_POST_INSTALL_TARGET_HOOKS += \
	DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT

# Only install process monitor and crontab if crond is installed
ifeq (y, $(BR2_PACKAGE_DCRON))
DIGITALROOSTERGUI_POST_INSTALL_TARGET_HOOKS += \
	DIGITALROOSTERGUI_POST_INSTALL_TARGET_SCRIPT_PROCMON
endif


$(eval $(cmake-package))
