#!/bin/sh
set -e

function sync_if_valid() {
	if [ 2019 -lt $(date +%Y) ] ;
	then
	    hwclock -u -w
	    [ $? = 0 ] && echo "OK" || echo "FAIL"
	else
    	    printf "Error: refusing to sync date from the past: %s !\n"  \
		   $(date +%Y-%m-%d)
	fi
}

echo "Synchronizing system clock to hardware clock ..."
sync_if_valid
